### ISSUE TITLE
Error: Cluster "no such endpoint"

### ISSUE THREAD

**Issue by screaser** [bzwheeler/amdash#10]
When running the 3-app setup, I see this error message in the console, from the term where I'm running the web-app:

W20151201-10:54:35.159(-5)? (STDERR) Cluster: no such endpoint for service:web

Maybe nothing, but thought I would record here in case it's something we should remedy.

**Comment by bzwheeler** [comment]
Hmm, 99% certain that is not an actual problem and is just something that occurs temporarily if you haven't started all 3 services or if a service gets restarted.  We are using the 'cluster' module to allow services to discover each other and when you change code and a service restarts, it is temporarily unable to be found.  Once it restarts, cluster is smart enough to find it again.
